name: k6 Load Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install k6 (via script)
        run: |
          curl -s https://packagecloud.io/install/repositories/loadimpact/k6/script.deb.sh | sudo bash
          sudo apt-get install -y k6
      - name: Run k6 load test
        run: k6 run tests/loadtest.js
