name: k6 Load Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  k6-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Homebrew
        run: |
          yes | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "eval \$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" >> $GITHUB_ENV
      - name: Install k6 via Homebrew
        run: |
          eval "$($(brew --prefix)/bin/brew shellenv)"
          brew install k6
      - name: Run k6 load test
        run: |
          eval "$($(brew --prefix)/bin/brew shellenv)"
          k6 run tests/loadtest.js
